Ironforge\TagBundle\Entity\Tag:
    type: entity
    table: tags
    repositoryClass: Ironforge\TagBundle\Doctrine\Repository\TagRepository
    fields:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
        name:
            type: string
            length: 255
        code:
            type: string
            length: 255
            unique: true
        createdAt:
            type: datetime
            column: created_at
    manyToMany:
        badges:
            targetEntity: Ironforge\AchievementBundle\Entity\Badge
            joinTable:
                name: badges_tags
                joinColumns:
                    tag_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    badge_id:
                        referencedColumnName: id
