parameters:
    ironforge.tag.repository.tag.class: Ironforge\TagBundle\Doctrine\Repository\TagRepository

services:
    ironforge.tag.repository.tag:
        class: %ironforge.tag.repository.tag.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Ironforge\TagBundle\Entity\Tag
