parameters:
    ironforge.game.saver.unlocked_badge.class: Ironforge\GameBundle\Doctrine\Saver\UnlockedBadgeSaver

services:
    ironforge.game.saver.badge:
        class: %ironforge.storage_utils.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Ironforge\GameBundle\Entity\Badge'

    ironforge.game.saver.unlocked_badge:
        class: %ironforge.game.saver.unlocked_badge.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - 'Ironforge\GameBundle\Entity\UnlockedBadge'

    ironforge.game.saver.claimed_badge:
        class: %ironforge.storage_utils.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Ironforge\GameBundle\Entity\ClaimedBadge'
