parameters:
    ironforge.user.repository.user.class: Ironforge\UserBundle\Doctrine\Repository\UserRepository

services:
    ironforge.user.repository.user:
        class: %ironforge.user.repository.user.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Ironforge\UserBundle\Entity\User
