Badger\Bundle\GameBundle\Entity\AdventureStepCompletion:
    type: entity
    table: adventure_step_completions
    repositoryClass: Badger\Bundle\GameBundle\Doctrine\Repository\AdventureStepCompletionRepository
    fields:
        id:
            id: true
            type: guid
            generator:
                strategy: UUID
        completionDate:
            type: datetime
            nullable: false
        pending:
            type: boolean
            nullable: false
    manyToOne:
        user:
            targetEntity: Badger\Bundle\UserBundle\Entity\User
            cascade: ['persist']
            joinColumn:
                user_id:
                    referencedColumnName: id
        step:
            targetEntity: Badger\Bundle\GameBundle\Entity\AdventureStep
            inversedBy: completions
            joinColumn:
                onDelete: cascade
                step_id:
                    referencedColumnName: id
    uniqueConstraints:
        only_one_completion_idx:
            columns: [ user_id, step_id ]
