Badger\Bundle\GameBundle\Entity\Tag:
    type: entity
    table: tags
    repositoryClass: Badger\Bundle\GameBundle\Doctrine\Repository\TagRepository
    fields:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
        name:
            type: string
            length: 255
        code:
            type: string
            length: 255
            unique: true
        isDefault:
            type: boolean
            name: is_default
        createdAt:
            type: datetime
            column: created_at
    manyToMany:
        badges:
            targetEntity: Badger\Bundle\GameBundle\Entity\Badge
            mappedBy: tags
        quests:
            targetEntity: Badger\Bundle\GameBundle\Entity\Quest
            mappedBy: tags
        adventures:
            targetEntity: Badger\Bundle\GameBundle\Entity\Adventure
            mappedBy: tags
