parameters:
    ironforge.achievement.badge.controller.class: Ironforge\AchievementBundle\Controller\BadgeController
    ironforge.achievement.claimed_badge.controller.class: Ironforge\AchievementBundle\Controller\ClaimedBadgeController
    ironforge.achievement.unlocked_badge.controller.class: Ironforge\AchievementBundle\Controller\UnlockedBadgeController

services:
    ironforge.achievement.badge.controller:
        class: %ironforge.achievement.badge.controller.class%
        calls:
            - [ setContainer, [ @service_container ] ]

    ironforge.achievement.claimed_badge.controller:
        class: %ironforge.achievement.claimed_badge.controller.class%
        calls:
            - [ setContainer, [ @service_container ] ]

    ironforge.achievement.unlocked_badge.controller:
        class: %ironforge.achievement.unlocked_badge.controller.class%
        calls:
            - [ setContainer, [ @service_container ] ]
