parameters:
    ironforge.achievement.badge.controller.class: Ironforge\AchievementBundle\Controller\BadgeController

services:
    ironforge.achievement.badge.controller:
        class: %ironforge.achievement.badge.controller.class%
        arguments:
            - '@fos_user.user_manager.default'
        calls:
            - [ setContainer, [ @service_container ] ]
