parameters:
    badger.game.saver.unlocked_badge.class: Badger\Bundle\GameBundle\Doctrine\Saver\UnlockedBadgeSaver

services:
    badger.game.saver.badge:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Badge'

    badger.game.saver.quest:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Quest'

    badger.game.saver.unlocked_badge:
        class: '%badger.game.saver.unlocked_badge.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - 'Badger\Bundle\GameBundle\Entity\UnlockedBadge'

    badger.game.saver.claimed_badge:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\ClaimedBadge'

    badger.game.saver.quest_completion:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\QuestCompletion'

    badger.game.saver.adventure:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\Adventure'

    badger.game.saver.adventure_step_completion:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\GameBundle\Entity\AdventureStepCompletion'
