parameters:
    badger.game.unlocker.badge.class: Badger\GameBundle\Unlocker\BadgeUnlocker

services:
    badger.game.unlocker.badge:
        class: '%badger.game.unlocker.badge.class%'
        arguments:
            - '@badger.game.unlocked_badge.factory'
            - '@badger.game.repository.unlocked_badge'
            - '@badger.game.saver.unlocked_badge'
            - '@badger.game.remover.claimed_badge'
