Badger\Bundle\GameBundle\Entity\Badge:
    properties:
        file:
            - File:
                maxSize: 6000000

Badger\Bundle\GameBundle\Entity\Tag:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: isDefault
            repositoryMethod: findByUniqueIsDefault
            message: tag.unique_is_default
