parameters:
    badger.game.badge.factory.class: Badger\GameBundle\Factory\BadgeFactory
    badger.game.quest.factory.class: Badger\GameBundle\Factory\QuestFactory
    badger.game.unlocked_badge.factory.class: Badger\GameBundle\Factory\UnlockedBadgeFactory
    badger.game.claimed_badge.factory.class: Badger\GameBundle\Factory\ClaimedBadgeFactory
    badger.game.configuration.factory.class: Badger\GameBundle\Factory\ConfigurationFactory
    badger.game.badge_proposal.factory.class: Badger\GameBundle\Factory\BadgeProposalFactory
    badger.game.badge_vote_summary.factory.class: Badger\GameBundle\Factory\BadgeVoteSummaryFactory

services:
    badger.game.badge.factory:
        class: '%badger.game.badge.factory.class%'

    badger.game.quest.factory:
        class: '%badger.game.quest.factory.class%'

    badger.game.unlocked_badge.factory:
        class: '%badger.game.unlocked_badge.factory.class%'

    badger.game.claimed_badge.factory:
        class: '%badger.game.claimed_badge.factory.class%'

    badger.game.configuration.factory:
        class: '%badger.game.configuration.factory.class%'

    badger.game.badge_proposal.factory:
        class: '%badger.game.badge_proposal.factory.class%'

    badger.game.badge_vote_summary.factory:
        class: '%badger.game.badge_vote_summary.factory.class%'
        arguments:
            - '@badger.game.repository.badge_proposal'
            - '@badger.game.repository.badge_vote'
