parameters:
    badger.game.repository.badge.class: Badger\GameBundle\Doctrine\Repository\BadgeRepository
    badger.game.repository.quest.class: Badger\GameBundle\Doctrine\Repository\QuestRepository
    badger.game.repository.claimed_badge.class: Badger\GameBundle\Doctrine\Repository\ClaimedBadgeRepository
    badger.game.repository.unlocked_badge.class: Badger\GameBundle\Doctrine\Repository\UnlockedBadgeRepository
    badger.game.repository.configuration.class: Badger\GameBundle\Doctrine\Repository\ConfigurationRepository

services:
    badger.game.repository.badge:
        class: '%badger.game.repository.badge.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\Badge

    badger.game.repository.quest:
        class: '%badger.game.repository.quest.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\Quest

    badger.game.repository.claimed_badge:
        class: '%badger.game.repository.claimed_badge.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\ClaimedBadge

    badger.game.repository.unlocked_badge:
        class: '%badger.game.repository.unlocked_badge.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\UnlockedBadge

    badger.game.repository.configuration:
        class: '%badger.game.repository.configuration.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\Configuration
