parameters:
    badger.game.saver.unlocked_badge.class: Badger\GameBundle\Doctrine\Saver\UnlockedBadgeSaver

services:
    badger.game.saver.badge:
        class: %badger.storage_utils.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\GameBundle\Entity\Badge'

    badger.game.saver.unlocked_badge:
        class: %badger.game.saver.unlocked_badge.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - 'Badger\GameBundle\Entity\UnlockedBadge'

    badger.game.saver.claimed_badge:
        class: %badger.storage_utils.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\GameBundle\Entity\ClaimedBadge'
