parameters:
    badger.game.twig.configuration.class: Badger\GameBundle\Twig\ConfigurationExtension
    badger.game.twig.vote.class: Badger\GameBundle\Twig\VoteExtension

services:
    badger.game.twig.configuration:
        class: '%badger.game.twig.configuration.class%'
        public: false
        arguments:
            - '@badger.game.repository.configuration'
        tags:
            - { name: twig.extension }

    badger.game.twig.vote:
        class: '%badger.game.twig.vote.class%'
        public: false
        tags:
            - { name: twig.extension }
