parameters:
    badger.game.helper.badge_vote_engine.class: Badger\GameBundle\Vote\BadgeVoteEngine
    badger.game.helper.badge_vote_summary.class: Badger\GameBundle\Vote\BadgeVoteSummary

services:
    badger.game.helper.badge_vote_engine:
        class: %badger.game.helper.badge_vote_engine.class%
        arguments:
            - '@badger.game.repository.badge_vote'
            - '@badger.game.remover.badge_vote'
            - '@badger.game.saver.badge_vote'

    badger.game.helper.badge_vote_summary:
        class: %badger.game.helper.badge_vote_summary.class%
