Ironforge\AchievementBundle\Entity\ClaimedBadge:
    type: entity
    table: claimed_badges
    repositoryClass: Ironforge\AchievementBundle\Doctrine\Repository\ClaimedBadgeRepository
    fields:
        id:
            id: true
            type: guid
            generator:
                strategy: UUID
        claimedDate:
            type: datetime
            nullable: false
    manyToOne:
        user:
            targetEntity: Ironforge\UserBundle\Entity\User
            joinColumn:
                user_id:
                    referencedColumnName: id
        badge:
            targetEntity: Ironforge\AchievementBundle\Entity\Badge
            joinColumn:
                badge_id:
                    referencedColumnName: id
