Ironforge\AchievementBundle\Entity\UnlockedBadge:
    type: entity
    table: unlocked_badges
    repositoryClass: Ironforge\AchievementBundle\Repository\UnlockedBadgeRepository
    fields:
        id:
            id: true
            type: guid
            generator:
                strategy: UUID
        unlockedDate:
            type: datetime
            nullable: false
    manyToOne:
        user:
            targetEntity: Ironforge\UserBundle\Entity\User
            joinColumn:
                user_id:
                    referencedColumnName: id
        badge:
            targetEntity: Ironforge\AchievementBundle\Entity\Badge
            joinColumn:
                badge_id:
                    referencedColumnName: id
