parameters:
    badger.user.repository.user.class: Badger\UserBundle\Doctrine\Repository\UserRepository

services:
    badger.user.repository.user:
        class: '%badger.user.repository.user.class%'
        factory: [doctrine.orm.entity_manager, getRepository]
        arguments:
            - Badger\UserBundle\Entity\User
