parameters:
    badger.user.repository.user.class: Badger\UserBundle\Doctrine\Repository\UserRepository

services:
    badger.user.repository.user:
        class: %badger.user.repository.user.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Badger\UserBundle\Entity\User
