admin_achievement_index:
    path:     /
    defaults: { _controller: "AchievementBundle:Achievement:index" }
    methods:  GET

admin_achievement_show:
    path:     /{id}/show
    defaults: { _controller: "AchievementBundle:Achievement:show" }
    methods:  GET

admin_achievement_new:
    path:     /new
    defaults: { _controller: "AchievementBundle:Achievement:new" }
    methods:  [GET, POST]

admin_achievement_edit:
    path:     /{id}/edit
    defaults: { _controller: "AchievementBundle:Achievement:edit" }
    methods:  [GET, POST]

admin_achievement_delete:
    path:     /{id}/delete
    defaults: { _controller: "AchievementBundle:Achievement:delete" }
    methods:  DELETE
