admin_unlocked_badge_new:
    path:     /new
    defaults: { _controller: "ironforge.achievement.unlocked_badge.controller:newAction" }
    methods:  [GET, POST]

admin_unlocked_badge_delete:
    path:     /delete
    defaults: { _controller: "ironforge.achievement.unlocked_badge.controller:deleteAction" }
    methods:  [GET, POST]
