badge_proposal_index:
    path:     /
    defaults: { _controller: "GameBundle:BadgeProposal:index" }
    methods:  GET

badge_proposal_new:
    path:     /new
    defaults: { _controller: "GameBundle:BadgeProposal:new" }
    methods:  [GET, POST]

badge_proposal_upvote:
    path:     /agree
    defaults: { _controller: "GameBundle:BadgeProposal:upvote" }
    methods:  [POST]
